### ISSUE TITLE
Android 12

### ISSUE THREAD

**Issue by maybejoe** [sckzw/AANotifier#2]
Hi,

I just updated to Android 12 (S21 ultra) and now I don't get notifications.

Will you be updating this for Android 12 support?

Thank you.

**Comment by maybejoe** [comment]
Edit: This may be a bug with AA and not AAnotifier.

**Comment by sckzw** [comment]
Hi,

I have checked and it works fine on Google Pixel 5a (Android 12). Android Auto version: 7.0.614134-release
Please make sure that "Notification access settings" and "Unknown sources" are enabled.

Thank you,

**Comment by sckzw** [comment]
Please try disabling the "Car mode" of this app.

**Comment by sckzw** [comment]
Workaround: Disable "Car mode" of this app.
暫定対策: このアプリの「車載モード」を無効にする。

This issue seems to be a bug in Android 12.
https://issuetracker.google.com/issues/207389461
https://github.com/sckzw/AANotifier/blob/ee5353cf0b139ab0674164737ea7bc034d7ab080/mobile/src/main/java/io/github/sckzw/aanotifier/MessagingService.java#L114-L116

**Comment by maybejoe** [comment]
Diabling car mode did not work for me but hopefully it works for others.

Waiting for google to fix the issue.

Thank you for the response.
